export const popularSnacks = [
  { snack_name: 'Banana', total_quantity: '30' },
  { snack_name: "M&M's", total_quantity: '614' },
  { snack_name: 'Lays - Original', total_quantity: '1' },
  { snack_name: 'Hi-Chew', total_quantity: '3' },
  { snack_name: 'testlays', total_quantity: '1' },
  { snack_name: 'Lays Ketchup', total_quantity: '1' },
  { snack_name: 'Freeze-dried Durian', total_quantity: '2' },
  { snack_name: 'Animal Crackers', total_quantity: '2' },
  { snack_name: 'Lays - Sour Cream & Onion', total_quantity: '2' },
  { snack_name: 'Coffee Crisp', total_quantity: '52' },
  { snack_name: 'Chocolate Milk', total_quantity: '221' },
  { snack_name: 'Baked Lays - Original', total_quantity: '3' },
  { snack_name: 'Brookies', total_quantity: '1' },
  { snack_name: 'Pepero', total_quantity: '102' },
  { snack_name: 'KitKat - Wasabi Flavour', total_quantity: '19' },
  { snack_name: 'Dried Mangoes', total_quantity: '1' },
  { snack_name: 'Apple', total_quantity: '1' },
  { snack_name: 'Taro Root', total_quantity: '10' },
  { snack_name: 'Cookie Cups', total_quantity: '1' },
  { snack_name: "Lay's", total_quantity: '1000' },
  { snack_name: 'Eggs', total_quantity: '2' },
  { snack_name: 'testleaf', total_quantity: '2' },
  { snack_name: 'KitKat', total_quantity: '1021' },
  { snack_name: 'friend', total_quantity: '3' },
  { snack_name: 'Smarties', total_quantity: '3' },
  { snack_name: 'SkyFlakes', total_quantity: '4' },
  { snack_name: 'in', total_quantity: '2' },
  { snack_name: 'High End Steak Cubes', total_quantity: '5' },
  { snack_name: 'Bark Thins', total_quantity: '4' },
  { snack_name: 'Profiteroles', total_quantity: '1' },
  { snack_name: 'Chocolate-dipped Strawberries', total_quantity: '32' },
  { snack_name: 'Vegetable Thins', total_quantity: '1' },
  { snack_name: 'The Marshmallow that Bob Left On The Table Last Week ',total_quantity: '1118' },
  { snack_name: 'A Bugs Life', total_quantity: '1' },
  { snack_name: 'Tomato', total_quantity: '997' }
]
